# Generated by Django 4.2.3 on 2023-08-02 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provincia',
            old_name='codigo',
            new_name='num_localidades',
        ),
    ]
